# Generated by Django 5.2 on 2025-04-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
